name: CI

on:
  push:
    tags:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9

    - name: Run tests
      shell: bash -l {0}
      run: |
        python3 setup.py install
        pip3 install -r requirements-test.txt
        python setup.py test
        pip3 install -r requirements-build.txt
        python setup.py build

    - name: Publish package to https://pypi.org/.
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}